name: Build and Release Windows App

on:
  push:
    branches:
      - master # Trigger on master branch changes
    paths:
      - 'package.json' # Trigger only on package.json changes

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: yarn install

    - name: Cache Yarn modules
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/yarn
          node_modules
        key: ${{ runner.os }}-yarn-cache
        restore-keys: |
          ${{ runner.os }}-yarn-cache

    - name: Build the Electron app
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: yarn build

    - name: Upload release assets
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
